[build-system]
requires = ["setuptools>=45", "wheel", "Cython", "numpy", "mpi4py"]
build-backend = "setuptools.build_meta"

[project]
name = "PyDDStore"
version = "2.0"
description = "Distributed Data Store"
requires-python = ">=3.6"
dependencies = ["numpy", "mpi4py"]

[project.optional-dependencies]
torch = ["torch"]
